spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ql_kitucxa"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days = 30*24*60*60
  secretKey: KaGTrWxigGRmBCJcN0zc7fs4DRR5iWoEieDtrun7CDs=
